name: External validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Validate
        uses: pnp/pnp-sample-validation@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
